version: "3.9"
services:
  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/simple-app:latest
    container_name: simple-app
    restart: always
    expose:
      - "8000"
    environment:
      APP_ENV: "production"
      